### ISSUE TITLE
local pwd not updated when using `wmv` command

### ISSUE THREAD

**Issue by dubrayn** [yssl/TWcmd.vim#2]
Hello and thanks for this nice plugin !

There seems to be an issue when using `:TWcmd wmv j` (or variants with `h`,`k` and `l`) : the window is moved as expected but the associated local pwd (which can be checked with `:pwd`) is not transfered to the new window location.

For example, if I open two buffers in a horizontal split, then type `:lcd /` for the top one and `:lcd /tmp` for the bottom one, then swap them using `:TWcmd wmv j`, the command `:pwd` for the top one returns `/` and the command `:pwd` for the bottom one returns `/tmp`, while the respective values `/tmp` and `/` are expected.

Let me know if I can help with this.

**Comment by yssl** [comment]
I apologize for the delayed response. 
Thank you for the valuable feedback. I wasn't aware of this issue since I don't use 'lcd' command.
I have updated the code to maintain the 'lcd' setting specified in the window for `:TWcmd wmv` and `:TWcmd wmvt` commands. 
Please test it with the latest code, and if you encounter any issues, please let me know. Thank you.

**Comment by dubrayn** [comment]
it works perfectly ! Thanks a lot.
